### ISSUE TITLE
Add helm support to install the MP and CP

### ISSUE THREAD

**Issue by boeboe** [tetratecx/tsb-single-vm#1]

**Comment by boeboe** [comment]
WIP on https://github.com/tetratecx/tsb-single-vm/tree/mp-cp-helm branch

**Comment by eitansuez** [comment]
i recently created a version of minitsb that installs mp and cp with helm.
feel free to reference https://github.com/eitansuez/minitsb-rake-helm in your work

**Comment by boeboe** [comment]
thanks @eitansuez 👍 .
helm support added.

**Comment by boeboe** [comment]
Implemented in https://github.com/tetratecx/tsb-single-vm/commit/5ef8ff29c17db47853db33442f997f5ce8a3e3c7

**Comment by boeboe** [comment]
https://github.com/tetratecx/tsb-single-vm/commit/5ef8ff29c17db47853db33442f997f5ce8a3e3c7
